// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/Icons/About.vue')['default']
    AriticleList: typeof import('./components/AriticleList.vue')['default']
    ArticleCard: typeof import('./components/ArticleCard.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    Back: typeof import('./components/Back.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Dark: typeof import('./components/Icons/Dark.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Github: typeof import('./components/Icons/Github.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Hello: typeof import('./components/hello.vue')['default']
    Home: typeof import('./components/Icons/Home.vue')['default']
    IconButtons: typeof import('./components/Icons/IconButtons.vue')['default']
    Language: typeof import('./components/Icons/Language.vue')['default']
    Profile: typeof import('./components/Profile.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./components/Icons/ScrollToTop.vue')['default']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    Tabs: typeof import('./components/Tabs.vue')['default']
  }
}
